### ISSUE TITLE
Lame-ass whining about code style - i am *that* guy

### ISSUE THREAD

**Issue by o-jasper** [jordan4ibanez/open_ai#14]
I guess you could just take it for what it is and close it ;) Thanks for being so prolific :) (and on minetest, and somewhat generally i am not, tho got some stuff offline)

* Smaller files is better. I.e. `git diff` the changes to which files tell a bit more. Also, less scrolling.

  Actually essentially only mean the long project goals header could be split off?

* Long tables.
  + Stuff that goes into a `minetest.register_` is kindah-like a class. Writing local `SomeClass = {}` and then `function SomeClass:some_method(...)` the first `self` is automatic with the `:` (incase you somehow missed this)

     Actually i think this is better in a different way than not having many-pages spanning tables; having such tables, you cannot simply write `local function fun_name(...)...end` in there, so it might subtly push against refactoring of that nature.(as it'd be scrolled-up a lot.)
  + Putting then in a `local ClassName = {...` in some cases, the automatic indentation works better.(though we can chafe this one off on the emacs indentation thingy i am using)

* Don't see anything in particular, maybe you're aware of the behavior. `or` returns the first non `nil`, non `false`.(and returns the last one otherwise) And `and` returns the last one, or the first `nil`/`false`. C/JS `cond ? yes : no` can be done with `(cond and yes) or no` for instance. It's on purpose :) i sometimes use it to cut down on conditional logic.

**Comment by jordan4ibanez** [comment]
Thank you for this comment! I am rewriting this to not only be a framework, but also a library that gets injected into the mob's entities to localize it for speed benefits. The library is stored globally and can be injected into entities from other mods. This will allow other mods to modify, add, improve, remove, etc functions in classes and benefit the code as a whole.
