### ISSUE TITLE
add a new tool that makes mobs bigger

### ISSUE THREAD

**Issue by 22i** [jordan4ibanez/open_ai#2]
There should be true false to determine whether mob is growable or resistant to it.

this tools should have limited uses

It could be growray - each time you use it on a mob it grows a bit until it becomes a giant that would also make mobs stronger and have more health more drops.

Some mobs can hold growray to grow other mobs.

and shrinkray that makes mobs smaller each rightclick with a shrinkray makes mob a bit smaller till it just disapears.

**Comment by jordan4ibanez** [comment]
Implimented as grow and shrink ray
